plugins {
    id "com.android.application"
}

android {
    namespace "com.yu1sh.androidusbmirror"
    compileSdk 35

    defaultConfig {
        applicationId "com.yu1sh.androidusbmirror"
        minSdk 29
        targetSdk 35
        versionCode 1
        versionName "0.1.0"
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    buildTypes {
        release {
            minifyEnabled false
            shrinkResources false
            proguardFiles getDefaultProguardFile("proguard-android-optimize.txt"), "proguard-rules.pro"
        }
    }
}
